### ISSUE TITLE
ReduceLinAlg fails to precompile in Julia 1.10

### ISSUE THREAD

**Issue by mattcbro** [reduce-algebra/reducelinalg.jl#2]
It hangs on "Waiting for background task / IO / timer.

 [bfcbc1eb] + ReduceLinAlg v0.1.0
Precompiling project...
  Progress [>                                        ]  0/1
  Progress [>                                        ]  0/1
^CProgress [>                                        ]  0/1
  ◑ ReduceLinAlg Waiting for background task / IO / timer. Interrupt to inspect
 Interrupted: Exiting precompilation...

  1 dependency had output during precompilation:
┌ ReduceLinAlg
│  [pid 386467] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   pipe[11]           0x1370710->0x7faa4787c6f0
│   process[386471]    0x16295a0->0x7faa476b06a0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.

**Comment by chakravala** [comment]
Thanks for reporting, this is probably an issue with `load_package` command defined in Reduce.jl and used in the `__init__` function of `ReduceLinAlg`, so I'm opening an issue over there https://github.com/chakravala/Reduce.jl/issues/58

**Comment by chakravala** [comment]
This problem is now fixed with `ReduceLinAlg` v0.1.1

**Comment by mattcbro** [comment]
Thanks for your rapid response to this.
